// AUTO-GENERATED by scripts/gen-locales.cjs — DO NOT EDIT BY HAND.
// 新增/删除语言：在 locales/ 增删 json 后重新运行脚本。

import { flattenLocale } from './flatten';

import raw0 from './zh-CN.json';
import raw1 from './en-US.json';
import raw2 from './es_ES.json';
import raw3 from './ja_JP.json';

export type LocaleId = 'zh-CN' | 'en-US' | 'es_ES' | 'ja_JP';

export const FALLBACK_LOCALE: LocaleId = 'zh-CN';

export const LOCALE_IDS: readonly LocaleId[] = ['zh-CN', 'en-US', 'es_ES', 'ja_JP'];

export const LOCALE_NAMES: Record<LocaleId, string> = {
  'zh-CN': '简体中文',
  'en-US': 'English(US)',
  es_ES: 'Español',
  ja_JP: '日本語',
};

export const MESSAGES: Record<LocaleId, Record<string, string>> = {
  'zh-CN': flattenLocale(raw0),
  'en-US': flattenLocale(raw1),
  es_ES: flattenLocale(raw2),
  ja_JP: flattenLocale(raw3),
};
