#!/usr/bin/env node
// 扫描 src/shared/i18n/locales/*.json，生成静态导入的 index.ts。
// - 递归打平嵌套对象：{ a: { b: 'x' } } → { 'a.b': 'x' }
// - 剔除 `_name`（语言显示名，单独输出到 LOCALE_NAMES）
// 用法：node scripts/gen-locales.cjs

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const DIR = path.join(ROOT, 'src/shared/i18n/locales');
const OUT = path.join(DIR, 'index.ts');
const FALLBACK = 'zh-CN';

if (!fs.existsSync(DIR)) {
  console.error(`[gen-locales] locales dir not found: ${DIR}`);
  process.exit(1);
}

const files = fs
  .readdirSync(DIR, { withFileTypes: true })
  .filter((e) => e.isFile() && e.name.endsWith('.json'))
  .map((e) => e.name)
  .sort();

if (!files.length) {
  console.error('[gen-locales] no .json files under locales/');
  process.exit(1);
}

const ids = files.map((f) => f.replace(/\.json$/, ''));
if (!ids.includes(FALLBACK)) {
  console.error(`[gen-locales] fallback locale "${FALLBACK}" is required`);
  process.exit(1);
}

/** 递归打平：{ a: { b: 'x' } } → { 'a.b': 'x' }；只保留字符串/数字/布尔。 */
function flatten(obj, prefix = '', out = {}) {
  for (const [key, value] of Object.entries(obj)) {
    if (key === '_name') continue;
    const path = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      flatten(value, path, out);
    } else if (value == null) {
      // null/undefined 跳过——词条里不该有它们
      continue;
    } else {
      out[path] = String(value);
    }
  }
  return out;
}

/** 读 JSON，提取语言显示名 + 扁平词条表。 */
function loadLocale(id) {
  const raw = JSON.parse(fs.readFileSync(path.join(DIR, `${id}.json`), 'utf8'));
  const name = typeof raw?._name === 'string' && raw._name.trim() ? raw._name.trim() : id;
  const dict = flatten(raw);
  return { name, dict };
}

const ordered = [FALLBACK, ...ids.filter((id) => id !== FALLBACK).sort()];
const loaded = ordered.map((id) => ({ id, ...loadLocale(id) }));

// 词条一致性检查：所有语言的 key 集合应完全相同（允许缺，但记警告）
const baseKeys = new Set(Object.keys(loaded[0].dict));
for (const { id, dict } of loaded.slice(1)) {
  const missing = [...baseKeys].filter((k) => !(k in dict));
  const extra = Object.keys(dict).filter((k) => !baseKeys.has(k));
  if (missing.length) console.warn(`[gen-locales] ${id} missing keys: ${missing.slice(0, 5).join(', ')}${missing.length > 5 ? '…' : ''}`);
  if (extra.length) console.warn(`[gen-locales] ${id} extra keys:   ${extra.slice(0, 5).join(', ')}${extra.length > 5 ? '…' : ''}`);
}

const importLines = loaded.map(({ id }, i) => `import raw${i} from './${id}.json';`).join('\n');
const idUnion = ordered.map((id) => JSON.stringify(id)).join(' | ');
const idList = ordered.map((id) => JSON.stringify(id)).join(', ');

const nameLines = loaded.map(({ id, name }) => `  ${JSON.stringify(id)}: ${JSON.stringify(name)},`).join('\n');

const content = `// AUTO-GENERATED by scripts/gen-locales.cjs — DO NOT EDIT BY HAND.
// 新增/删除语言：在 locales/ 增删 json 后重新运行脚本。

import { flattenLocale } from './flatten';

${importLines}

export type LocaleId = ${idUnion};

export const FALLBACK_LOCALE: LocaleId = ${JSON.stringify(FALLBACK)};

export const LOCALE_IDS: readonly LocaleId[] = [${idList}];

export const LOCALE_NAMES: Record<LocaleId, string> = {
${nameLines}
};

export const MESSAGES: Record<LocaleId, Record<string, string>> = {
${loaded.map(({ id }, i) => `  ${JSON.stringify(id)}: flattenLocale(raw${i}),`).join('\n')}
};
`;

fs.writeFileSync(OUT, content, 'utf8');
console.log(`[gen-locales] ${path.relative(ROOT, OUT)} (${ordered.length} locales: ${ordered.join(', ')})`);
